apiVersion: v1
kind: Service
metadata:
  name: redis-cache
  namespace: crypto-platform
  labels:
    app: redis-cache
spec:
  selector:
    app: redis-cache
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-market
  namespace: crypto-platform
  labels:
    app: redis-market
spec:
  selector:
    app: redis-market
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
