apiVersion: v1
kind: Service
metadata:
  name: market-service
  namespace: crypto-platform
  labels:
    app: market-service
spec:
  selector:
    app: market-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
  type: ClusterIP
